package com.tlv8.system.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class SaOprole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA_OPROLE.SID
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA_OPROLE.SNAME
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA_OPROLE.SCODE
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    private String scode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA_OPROLE.SCATALOG
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    private String scatalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA_OPROLE.SROLEKIND
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    private String srolekind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA_OPROLE.SPARENTROLESNAMES
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    private String sparentrolesnames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA_OPROLE.SDESCRIPTION
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    private String sdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA_OPROLE.SSEQUENCE
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    private BigDecimal ssequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA_OPROLE.SVALIDSTATE
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    private BigDecimal svalidstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SA_OPROLE.VERSION
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    private BigDecimal version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SA_OPROLE
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SA_OPROLE.SID
     *
     * @return the value of SA_OPROLE.SID
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SA_OPROLE.SID
     *
     * @param sid the value for SA_OPROLE.SID
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SA_OPROLE.SNAME
     *
     * @return the value of SA_OPROLE.SNAME
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SA_OPROLE.SNAME
     *
     * @param sname the value for SA_OPROLE.SNAME
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SA_OPROLE.SCODE
     *
     * @return the value of SA_OPROLE.SCODE
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public String getScode() {
        return scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SA_OPROLE.SCODE
     *
     * @param scode the value for SA_OPROLE.SCODE
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public void setScode(String scode) {
        this.scode = scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SA_OPROLE.SCATALOG
     *
     * @return the value of SA_OPROLE.SCATALOG
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public String getScatalog() {
        return scatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SA_OPROLE.SCATALOG
     *
     * @param scatalog the value for SA_OPROLE.SCATALOG
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public void setScatalog(String scatalog) {
        this.scatalog = scatalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SA_OPROLE.SROLEKIND
     *
     * @return the value of SA_OPROLE.SROLEKIND
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public String getSrolekind() {
        return srolekind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SA_OPROLE.SROLEKIND
     *
     * @param srolekind the value for SA_OPROLE.SROLEKIND
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public void setSrolekind(String srolekind) {
        this.srolekind = srolekind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SA_OPROLE.SPARENTROLESNAMES
     *
     * @return the value of SA_OPROLE.SPARENTROLESNAMES
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public String getSparentrolesnames() {
        return sparentrolesnames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SA_OPROLE.SPARENTROLESNAMES
     *
     * @param sparentrolesnames the value for SA_OPROLE.SPARENTROLESNAMES
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public void setSparentrolesnames(String sparentrolesnames) {
        this.sparentrolesnames = sparentrolesnames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SA_OPROLE.SDESCRIPTION
     *
     * @return the value of SA_OPROLE.SDESCRIPTION
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public String getSdescription() {
        return sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SA_OPROLE.SDESCRIPTION
     *
     * @param sdescription the value for SA_OPROLE.SDESCRIPTION
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public void setSdescription(String sdescription) {
        this.sdescription = sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SA_OPROLE.SSEQUENCE
     *
     * @return the value of SA_OPROLE.SSEQUENCE
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public BigDecimal getSsequence() {
        return ssequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SA_OPROLE.SSEQUENCE
     *
     * @param ssequence the value for SA_OPROLE.SSEQUENCE
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public void setSsequence(BigDecimal ssequence) {
        this.ssequence = ssequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SA_OPROLE.SVALIDSTATE
     *
     * @return the value of SA_OPROLE.SVALIDSTATE
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public BigDecimal getSvalidstate() {
        return svalidstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SA_OPROLE.SVALIDSTATE
     *
     * @param svalidstate the value for SA_OPROLE.SVALIDSTATE
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public void setSvalidstate(BigDecimal svalidstate) {
        this.svalidstate = svalidstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SA_OPROLE.VERSION
     *
     * @return the value of SA_OPROLE.VERSION
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SA_OPROLE.VERSION
     *
     * @param version the value for SA_OPROLE.VERSION
     *
     * @mbg.generated Fri Dec 01 10:00:32 CST 2023
     */
    public void setVersion(BigDecimal version) {
        this.version = version;
    }
}