package com.tlv8.system.pojo;

import java.io.Serializable;

public class SaOporg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SCODE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String scode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SLONGNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String slongname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SFNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sfname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SFCODE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sfcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SFID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sfid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SORGKINDID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sorgkindid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SVALIDSTATE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private Integer svalidstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SPARENT
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sparent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SLEVEL
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private Integer slevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SPHONE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SFAX
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sfax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SADDRESS
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String saddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SZIP
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String szip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SDESCRIPTION
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SPERSONID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String spersonid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SNODEKIND
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String snodekind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.VERSION
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SSHOWNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sshowname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oporg.SSEQUENCE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private Integer ssequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa_oporg
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SID
     *
     * @return the value of sa_oporg.SID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SID
     *
     * @param sid the value for sa_oporg.SID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SNAME
     *
     * @return the value of sa_oporg.SNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SNAME
     *
     * @param sname the value for sa_oporg.SNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SCODE
     *
     * @return the value of sa_oporg.SCODE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getScode() {
        return scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SCODE
     *
     * @param scode the value for sa_oporg.SCODE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setScode(String scode) {
        this.scode = scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SLONGNAME
     *
     * @return the value of sa_oporg.SLONGNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSlongname() {
        return slongname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SLONGNAME
     *
     * @param slongname the value for sa_oporg.SLONGNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSlongname(String slongname) {
        this.slongname = slongname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SFNAME
     *
     * @return the value of sa_oporg.SFNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSfname() {
        return sfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SFNAME
     *
     * @param sfname the value for sa_oporg.SFNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSfname(String sfname) {
        this.sfname = sfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SFCODE
     *
     * @return the value of sa_oporg.SFCODE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSfcode() {
        return sfcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SFCODE
     *
     * @param sfcode the value for sa_oporg.SFCODE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSfcode(String sfcode) {
        this.sfcode = sfcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SFID
     *
     * @return the value of sa_oporg.SFID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSfid() {
        return sfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SFID
     *
     * @param sfid the value for sa_oporg.SFID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSfid(String sfid) {
        this.sfid = sfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SORGKINDID
     *
     * @return the value of sa_oporg.SORGKINDID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSorgkindid() {
        return sorgkindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SORGKINDID
     *
     * @param sorgkindid the value for sa_oporg.SORGKINDID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSorgkindid(String sorgkindid) {
        this.sorgkindid = sorgkindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SVALIDSTATE
     *
     * @return the value of sa_oporg.SVALIDSTATE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public Integer getSvalidstate() {
        return svalidstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SVALIDSTATE
     *
     * @param svalidstate the value for sa_oporg.SVALIDSTATE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSvalidstate(Integer svalidstate) {
        this.svalidstate = svalidstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SPARENT
     *
     * @return the value of sa_oporg.SPARENT
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSparent() {
        return sparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SPARENT
     *
     * @param sparent the value for sa_oporg.SPARENT
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSparent(String sparent) {
        this.sparent = sparent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SLEVEL
     *
     * @return the value of sa_oporg.SLEVEL
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public Integer getSlevel() {
        return slevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SLEVEL
     *
     * @param slevel the value for sa_oporg.SLEVEL
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSlevel(Integer slevel) {
        this.slevel = slevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SPHONE
     *
     * @return the value of sa_oporg.SPHONE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSphone() {
        return sphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SPHONE
     *
     * @param sphone the value for sa_oporg.SPHONE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSphone(String sphone) {
        this.sphone = sphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SFAX
     *
     * @return the value of sa_oporg.SFAX
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSfax() {
        return sfax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SFAX
     *
     * @param sfax the value for sa_oporg.SFAX
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSfax(String sfax) {
        this.sfax = sfax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SADDRESS
     *
     * @return the value of sa_oporg.SADDRESS
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSaddress() {
        return saddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SADDRESS
     *
     * @param saddress the value for sa_oporg.SADDRESS
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSaddress(String saddress) {
        this.saddress = saddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SZIP
     *
     * @return the value of sa_oporg.SZIP
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSzip() {
        return szip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SZIP
     *
     * @param szip the value for sa_oporg.SZIP
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSzip(String szip) {
        this.szip = szip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SDESCRIPTION
     *
     * @return the value of sa_oporg.SDESCRIPTION
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSdescription() {
        return sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SDESCRIPTION
     *
     * @param sdescription the value for sa_oporg.SDESCRIPTION
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSdescription(String sdescription) {
        this.sdescription = sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SPERSONID
     *
     * @return the value of sa_oporg.SPERSONID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSpersonid() {
        return spersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SPERSONID
     *
     * @param spersonid the value for sa_oporg.SPERSONID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSpersonid(String spersonid) {
        this.spersonid = spersonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SNODEKIND
     *
     * @return the value of sa_oporg.SNODEKIND
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSnodekind() {
        return snodekind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SNODEKIND
     *
     * @param snodekind the value for sa_oporg.SNODEKIND
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSnodekind(String snodekind) {
        this.snodekind = snodekind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.VERSION
     *
     * @return the value of sa_oporg.VERSION
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.VERSION
     *
     * @param version the value for sa_oporg.VERSION
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SSHOWNAME
     *
     * @return the value of sa_oporg.SSHOWNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSshowname() {
        return sshowname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SSHOWNAME
     *
     * @param sshowname the value for sa_oporg.SSHOWNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSshowname(String sshowname) {
        this.sshowname = sshowname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oporg.SSEQUENCE
     *
     * @return the value of sa_oporg.SSEQUENCE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public Integer getSsequence() {
        return ssequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oporg.SSEQUENCE
     *
     * @param ssequence the value for sa_oporg.SSEQUENCE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSsequence(Integer ssequence) {
        this.ssequence = ssequence;
    }
}