package com.tlv8.system.pojo;

import java.io.Serializable;

public class SaOppermission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oppermission.SID
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oppermission.SPERMISSIONROLEID
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private String spermissionroleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oppermission.SPROCESS
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private String sprocess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oppermission.SACTIVITYFNAME
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private String sactivityfname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oppermission.SACTIVITY
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private String sactivity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oppermission.SSEMANTICDP
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private String ssemanticdp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oppermission.SPERMISSIONKIND
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private Integer spermissionkind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oppermission.SDESCRIPTION
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private String sdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oppermission.SSEQUENCE
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private Integer ssequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oppermission.SVALIDSTATE
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private Integer svalidstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oppermission.VERSION
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oppermission.SACTIONSNAMES
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private String sactionsnames;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_oppermission.SACTIONS
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private String sactions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa_oppermission
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oppermission.SID
     *
     * @return the value of sa_oppermission.SID
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oppermission.SID
     *
     * @param sid the value for sa_oppermission.SID
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oppermission.SPERMISSIONROLEID
     *
     * @return the value of sa_oppermission.SPERMISSIONROLEID
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public String getSpermissionroleid() {
        return spermissionroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oppermission.SPERMISSIONROLEID
     *
     * @param spermissionroleid the value for sa_oppermission.SPERMISSIONROLEID
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public void setSpermissionroleid(String spermissionroleid) {
        this.spermissionroleid = spermissionroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oppermission.SPROCESS
     *
     * @return the value of sa_oppermission.SPROCESS
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public String getSprocess() {
        return sprocess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oppermission.SPROCESS
     *
     * @param sprocess the value for sa_oppermission.SPROCESS
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public void setSprocess(String sprocess) {
        this.sprocess = sprocess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oppermission.SACTIVITYFNAME
     *
     * @return the value of sa_oppermission.SACTIVITYFNAME
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public String getSactivityfname() {
        return sactivityfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oppermission.SACTIVITYFNAME
     *
     * @param sactivityfname the value for sa_oppermission.SACTIVITYFNAME
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public void setSactivityfname(String sactivityfname) {
        this.sactivityfname = sactivityfname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oppermission.SACTIVITY
     *
     * @return the value of sa_oppermission.SACTIVITY
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public String getSactivity() {
        return sactivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oppermission.SACTIVITY
     *
     * @param sactivity the value for sa_oppermission.SACTIVITY
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public void setSactivity(String sactivity) {
        this.sactivity = sactivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oppermission.SSEMANTICDP
     *
     * @return the value of sa_oppermission.SSEMANTICDP
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public String getSsemanticdp() {
        return ssemanticdp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oppermission.SSEMANTICDP
     *
     * @param ssemanticdp the value for sa_oppermission.SSEMANTICDP
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public void setSsemanticdp(String ssemanticdp) {
        this.ssemanticdp = ssemanticdp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oppermission.SPERMISSIONKIND
     *
     * @return the value of sa_oppermission.SPERMISSIONKIND
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public Integer getSpermissionkind() {
        return spermissionkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oppermission.SPERMISSIONKIND
     *
     * @param spermissionkind the value for sa_oppermission.SPERMISSIONKIND
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public void setSpermissionkind(Integer spermissionkind) {
        this.spermissionkind = spermissionkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oppermission.SDESCRIPTION
     *
     * @return the value of sa_oppermission.SDESCRIPTION
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public String getSdescription() {
        return sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oppermission.SDESCRIPTION
     *
     * @param sdescription the value for sa_oppermission.SDESCRIPTION
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public void setSdescription(String sdescription) {
        this.sdescription = sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oppermission.SSEQUENCE
     *
     * @return the value of sa_oppermission.SSEQUENCE
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public Integer getSsequence() {
        return ssequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oppermission.SSEQUENCE
     *
     * @param ssequence the value for sa_oppermission.SSEQUENCE
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public void setSsequence(Integer ssequence) {
        this.ssequence = ssequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oppermission.SVALIDSTATE
     *
     * @return the value of sa_oppermission.SVALIDSTATE
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public Integer getSvalidstate() {
        return svalidstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oppermission.SVALIDSTATE
     *
     * @param svalidstate the value for sa_oppermission.SVALIDSTATE
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public void setSvalidstate(Integer svalidstate) {
        this.svalidstate = svalidstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oppermission.VERSION
     *
     * @return the value of sa_oppermission.VERSION
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oppermission.VERSION
     *
     * @param version the value for sa_oppermission.VERSION
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oppermission.SACTIONSNAMES
     *
     * @return the value of sa_oppermission.SACTIONSNAMES
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public String getSactionsnames() {
        return sactionsnames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oppermission.SACTIONSNAMES
     *
     * @param sactionsnames the value for sa_oppermission.SACTIONSNAMES
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public void setSactionsnames(String sactionsnames) {
        this.sactionsnames = sactionsnames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_oppermission.SACTIONS
     *
     * @return the value of sa_oppermission.SACTIONS
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public String getSactions() {
        return sactions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_oppermission.SACTIONS
     *
     * @param sactions the value for sa_oppermission.SACTIONS
     *
     * @mbg.generated Wed Dec 20 16:45:11 CST 2023
     */
    public void setSactions(String sactions) {
        this.sactions = sactions;
    }
}