package com.tlv8.system.pojo;

import java.io.Serializable;
import java.util.Date;

public class SaOpperson implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SCODE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String scode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SIDCARD
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sidcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SNUMB
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private Integer snumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SLOGINNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sloginname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SPASSWORD
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String spassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SPASSWORDTIMELIMIT
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private Integer spasswordtimelimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SPASSWORDMODIFYTIME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private Date spasswordmodifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SMAINORGID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String smainorgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SSAFELEVELID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String ssafelevelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SSEQUENCE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private Integer ssequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SVALIDSTATE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private Integer svalidstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SDESCRIPTION
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SSEX
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String ssex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SBIRTHDAY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private Date sbirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SJOINDATE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private Date sjoindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SHOMEPLACE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String shomeplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SDEGREE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sdegree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SGRADUATESCHOOL
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sgraduateschool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SSPECIALITY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sspeciality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SSCHOOLLENGTH
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sschoollength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.STITLE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String stitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SMARRIAGE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String smarriage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SCARDNO
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String scardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SCARDKIND
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String scardkind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SFAMILYADDRESS
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sfamilyaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SZIP
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String szip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SMSN
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String smsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SQQ
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sqq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SMAIL
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String smail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SMOBILEPHONE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String smobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SFAMILYPHONE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sfamilyphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SOFFICEPHONE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sofficephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.VERSION
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SCOUNTRY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String scountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SPROVINCE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SCITY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String scity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SPOSITIONS
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String spositions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SSCHOOL
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sschool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SSTUDY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String sstudy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SENGLISHNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String senglishname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.FCASN
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String fcasn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.FSIGNM
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private String fsignm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sa_opperson.SPHOTO
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private byte[] sphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sa_opperson
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SID
     *
     * @return the value of sa_opperson.SID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SID
     *
     * @param sid the value for sa_opperson.SID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SNAME
     *
     * @return the value of sa_opperson.SNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SNAME
     *
     * @param sname the value for sa_opperson.SNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSname(String sname) {
        this.sname = sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SCODE
     *
     * @return the value of sa_opperson.SCODE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getScode() {
        return scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SCODE
     *
     * @param scode the value for sa_opperson.SCODE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setScode(String scode) {
        this.scode = scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SIDCARD
     *
     * @return the value of sa_opperson.SIDCARD
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSidcard() {
        return sidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SIDCARD
     *
     * @param sidcard the value for sa_opperson.SIDCARD
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSidcard(String sidcard) {
        this.sidcard = sidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SNUMB
     *
     * @return the value of sa_opperson.SNUMB
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public Integer getSnumb() {
        return snumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SNUMB
     *
     * @param snumb the value for sa_opperson.SNUMB
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSnumb(Integer snumb) {
        this.snumb = snumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SLOGINNAME
     *
     * @return the value of sa_opperson.SLOGINNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSloginname() {
        return sloginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SLOGINNAME
     *
     * @param sloginname the value for sa_opperson.SLOGINNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSloginname(String sloginname) {
        this.sloginname = sloginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SPASSWORD
     *
     * @return the value of sa_opperson.SPASSWORD
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSpassword() {
        return spassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SPASSWORD
     *
     * @param spassword the value for sa_opperson.SPASSWORD
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSpassword(String spassword) {
        this.spassword = spassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SPASSWORDTIMELIMIT
     *
     * @return the value of sa_opperson.SPASSWORDTIMELIMIT
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public Integer getSpasswordtimelimit() {
        return spasswordtimelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SPASSWORDTIMELIMIT
     *
     * @param spasswordtimelimit the value for sa_opperson.SPASSWORDTIMELIMIT
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSpasswordtimelimit(Integer spasswordtimelimit) {
        this.spasswordtimelimit = spasswordtimelimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SPASSWORDMODIFYTIME
     *
     * @return the value of sa_opperson.SPASSWORDMODIFYTIME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public Date getSpasswordmodifytime() {
        return spasswordmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SPASSWORDMODIFYTIME
     *
     * @param spasswordmodifytime the value for sa_opperson.SPASSWORDMODIFYTIME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSpasswordmodifytime(Date spasswordmodifytime) {
        this.spasswordmodifytime = spasswordmodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SMAINORGID
     *
     * @return the value of sa_opperson.SMAINORGID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSmainorgid() {
        return smainorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SMAINORGID
     *
     * @param smainorgid the value for sa_opperson.SMAINORGID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSmainorgid(String smainorgid) {
        this.smainorgid = smainorgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SSAFELEVELID
     *
     * @return the value of sa_opperson.SSAFELEVELID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSsafelevelid() {
        return ssafelevelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SSAFELEVELID
     *
     * @param ssafelevelid the value for sa_opperson.SSAFELEVELID
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSsafelevelid(String ssafelevelid) {
        this.ssafelevelid = ssafelevelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SSEQUENCE
     *
     * @return the value of sa_opperson.SSEQUENCE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public Integer getSsequence() {
        return ssequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SSEQUENCE
     *
     * @param ssequence the value for sa_opperson.SSEQUENCE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSsequence(Integer ssequence) {
        this.ssequence = ssequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SVALIDSTATE
     *
     * @return the value of sa_opperson.SVALIDSTATE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public Integer getSvalidstate() {
        return svalidstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SVALIDSTATE
     *
     * @param svalidstate the value for sa_opperson.SVALIDSTATE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSvalidstate(Integer svalidstate) {
        this.svalidstate = svalidstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SDESCRIPTION
     *
     * @return the value of sa_opperson.SDESCRIPTION
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSdescription() {
        return sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SDESCRIPTION
     *
     * @param sdescription the value for sa_opperson.SDESCRIPTION
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSdescription(String sdescription) {
        this.sdescription = sdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SSEX
     *
     * @return the value of sa_opperson.SSEX
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SSEX
     *
     * @param ssex the value for sa_opperson.SSEX
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSsex(String ssex) {
        this.ssex = ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SBIRTHDAY
     *
     * @return the value of sa_opperson.SBIRTHDAY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public Date getSbirthday() {
        return sbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SBIRTHDAY
     *
     * @param sbirthday the value for sa_opperson.SBIRTHDAY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSbirthday(Date sbirthday) {
        this.sbirthday = sbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SJOINDATE
     *
     * @return the value of sa_opperson.SJOINDATE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public Date getSjoindate() {
        return sjoindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SJOINDATE
     *
     * @param sjoindate the value for sa_opperson.SJOINDATE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSjoindate(Date sjoindate) {
        this.sjoindate = sjoindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SHOMEPLACE
     *
     * @return the value of sa_opperson.SHOMEPLACE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getShomeplace() {
        return shomeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SHOMEPLACE
     *
     * @param shomeplace the value for sa_opperson.SHOMEPLACE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setShomeplace(String shomeplace) {
        this.shomeplace = shomeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SDEGREE
     *
     * @return the value of sa_opperson.SDEGREE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSdegree() {
        return sdegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SDEGREE
     *
     * @param sdegree the value for sa_opperson.SDEGREE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSdegree(String sdegree) {
        this.sdegree = sdegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SGRADUATESCHOOL
     *
     * @return the value of sa_opperson.SGRADUATESCHOOL
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSgraduateschool() {
        return sgraduateschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SGRADUATESCHOOL
     *
     * @param sgraduateschool the value for sa_opperson.SGRADUATESCHOOL
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSgraduateschool(String sgraduateschool) {
        this.sgraduateschool = sgraduateschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SSPECIALITY
     *
     * @return the value of sa_opperson.SSPECIALITY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSspeciality() {
        return sspeciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SSPECIALITY
     *
     * @param sspeciality the value for sa_opperson.SSPECIALITY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSspeciality(String sspeciality) {
        this.sspeciality = sspeciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SSCHOOLLENGTH
     *
     * @return the value of sa_opperson.SSCHOOLLENGTH
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSschoollength() {
        return sschoollength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SSCHOOLLENGTH
     *
     * @param sschoollength the value for sa_opperson.SSCHOOLLENGTH
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSschoollength(String sschoollength) {
        this.sschoollength = sschoollength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.STITLE
     *
     * @return the value of sa_opperson.STITLE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getStitle() {
        return stitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.STITLE
     *
     * @param stitle the value for sa_opperson.STITLE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setStitle(String stitle) {
        this.stitle = stitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SMARRIAGE
     *
     * @return the value of sa_opperson.SMARRIAGE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSmarriage() {
        return smarriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SMARRIAGE
     *
     * @param smarriage the value for sa_opperson.SMARRIAGE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSmarriage(String smarriage) {
        this.smarriage = smarriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SCARDNO
     *
     * @return the value of sa_opperson.SCARDNO
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getScardno() {
        return scardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SCARDNO
     *
     * @param scardno the value for sa_opperson.SCARDNO
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setScardno(String scardno) {
        this.scardno = scardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SCARDKIND
     *
     * @return the value of sa_opperson.SCARDKIND
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getScardkind() {
        return scardkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SCARDKIND
     *
     * @param scardkind the value for sa_opperson.SCARDKIND
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setScardkind(String scardkind) {
        this.scardkind = scardkind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SFAMILYADDRESS
     *
     * @return the value of sa_opperson.SFAMILYADDRESS
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSfamilyaddress() {
        return sfamilyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SFAMILYADDRESS
     *
     * @param sfamilyaddress the value for sa_opperson.SFAMILYADDRESS
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSfamilyaddress(String sfamilyaddress) {
        this.sfamilyaddress = sfamilyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SZIP
     *
     * @return the value of sa_opperson.SZIP
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSzip() {
        return szip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SZIP
     *
     * @param szip the value for sa_opperson.SZIP
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSzip(String szip) {
        this.szip = szip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SMSN
     *
     * @return the value of sa_opperson.SMSN
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSmsn() {
        return smsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SMSN
     *
     * @param smsn the value for sa_opperson.SMSN
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSmsn(String smsn) {
        this.smsn = smsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SQQ
     *
     * @return the value of sa_opperson.SQQ
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSqq() {
        return sqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SQQ
     *
     * @param sqq the value for sa_opperson.SQQ
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSqq(String sqq) {
        this.sqq = sqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SMAIL
     *
     * @return the value of sa_opperson.SMAIL
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSmail() {
        return smail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SMAIL
     *
     * @param smail the value for sa_opperson.SMAIL
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSmail(String smail) {
        this.smail = smail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SMOBILEPHONE
     *
     * @return the value of sa_opperson.SMOBILEPHONE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSmobilephone() {
        return smobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SMOBILEPHONE
     *
     * @param smobilephone the value for sa_opperson.SMOBILEPHONE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSmobilephone(String smobilephone) {
        this.smobilephone = smobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SFAMILYPHONE
     *
     * @return the value of sa_opperson.SFAMILYPHONE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSfamilyphone() {
        return sfamilyphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SFAMILYPHONE
     *
     * @param sfamilyphone the value for sa_opperson.SFAMILYPHONE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSfamilyphone(String sfamilyphone) {
        this.sfamilyphone = sfamilyphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SOFFICEPHONE
     *
     * @return the value of sa_opperson.SOFFICEPHONE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSofficephone() {
        return sofficephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SOFFICEPHONE
     *
     * @param sofficephone the value for sa_opperson.SOFFICEPHONE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSofficephone(String sofficephone) {
        this.sofficephone = sofficephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.VERSION
     *
     * @return the value of sa_opperson.VERSION
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.VERSION
     *
     * @param version the value for sa_opperson.VERSION
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SCOUNTRY
     *
     * @return the value of sa_opperson.SCOUNTRY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getScountry() {
        return scountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SCOUNTRY
     *
     * @param scountry the value for sa_opperson.SCOUNTRY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setScountry(String scountry) {
        this.scountry = scountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SPROVINCE
     *
     * @return the value of sa_opperson.SPROVINCE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSprovince() {
        return sprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SPROVINCE
     *
     * @param sprovince the value for sa_opperson.SPROVINCE
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSprovince(String sprovince) {
        this.sprovince = sprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SCITY
     *
     * @return the value of sa_opperson.SCITY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getScity() {
        return scity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SCITY
     *
     * @param scity the value for sa_opperson.SCITY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setScity(String scity) {
        this.scity = scity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SPOSITIONS
     *
     * @return the value of sa_opperson.SPOSITIONS
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSpositions() {
        return spositions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SPOSITIONS
     *
     * @param spositions the value for sa_opperson.SPOSITIONS
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSpositions(String spositions) {
        this.spositions = spositions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SSCHOOL
     *
     * @return the value of sa_opperson.SSCHOOL
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSschool() {
        return sschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SSCHOOL
     *
     * @param sschool the value for sa_opperson.SSCHOOL
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSschool(String sschool) {
        this.sschool = sschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SSTUDY
     *
     * @return the value of sa_opperson.SSTUDY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSstudy() {
        return sstudy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SSTUDY
     *
     * @param sstudy the value for sa_opperson.SSTUDY
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSstudy(String sstudy) {
        this.sstudy = sstudy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SENGLISHNAME
     *
     * @return the value of sa_opperson.SENGLISHNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getSenglishname() {
        return senglishname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SENGLISHNAME
     *
     * @param senglishname the value for sa_opperson.SENGLISHNAME
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSenglishname(String senglishname) {
        this.senglishname = senglishname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.FCASN
     *
     * @return the value of sa_opperson.FCASN
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getFcasn() {
        return fcasn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.FCASN
     *
     * @param fcasn the value for sa_opperson.FCASN
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setFcasn(String fcasn) {
        this.fcasn = fcasn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.FSIGNM
     *
     * @return the value of sa_opperson.FSIGNM
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public String getFsignm() {
        return fsignm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.FSIGNM
     *
     * @param fsignm the value for sa_opperson.FSIGNM
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setFsignm(String fsignm) {
        this.fsignm = fsignm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sa_opperson.SPHOTO
     *
     * @return the value of sa_opperson.SPHOTO
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public byte[] getSphoto() {
        return sphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sa_opperson.SPHOTO
     *
     * @param sphoto the value for sa_opperson.SPHOTO
     *
     * @mbg.generated Sat Nov 23 13:03:29 CST 2024
     */
    public void setSphoto(byte[] sphoto) {
        this.sphoto = sphoto;
    }
}