package com.tlv8.oa.mapper;

import com.tlv8.oa.pojo.OaTest1;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface OaTest1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_TEST1
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    int deleteByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_TEST1
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    int insert(OaTest1 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_TEST1
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    OaTest1 selectByPrimaryKey(String fid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_TEST1
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    List<OaTest1> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OA_TEST1
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    int updateByPrimaryKey(OaTest1 row);
}