package com.tlv8.oa.pojo;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class OaTest1 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEST1.FID
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    private String fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEST1.FMINGCHENG
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    private String fmingcheng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEST1.VERSION
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    private BigDecimal version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEST1.CODE
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEST1.SCODE
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    private String scode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEST1.FDATE
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    private Date fdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column OA_TEST1.FBILLID
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    private String fbillid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table OA_TEST1
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEST1.FID
     *
     * @return the value of OA_TEST1.FID
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEST1.FID
     *
     * @param fid the value for OA_TEST1.FID
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public void setFid(String fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEST1.FMINGCHENG
     *
     * @return the value of OA_TEST1.FMINGCHENG
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public String getFmingcheng() {
        return fmingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEST1.FMINGCHENG
     *
     * @param fmingcheng the value for OA_TEST1.FMINGCHENG
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public void setFmingcheng(String fmingcheng) {
        this.fmingcheng = fmingcheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEST1.VERSION
     *
     * @return the value of OA_TEST1.VERSION
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public BigDecimal getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEST1.VERSION
     *
     * @param version the value for OA_TEST1.VERSION
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public void setVersion(BigDecimal version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEST1.CODE
     *
     * @return the value of OA_TEST1.CODE
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEST1.CODE
     *
     * @param code the value for OA_TEST1.CODE
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEST1.SCODE
     *
     * @return the value of OA_TEST1.SCODE
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public String getScode() {
        return scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEST1.SCODE
     *
     * @param scode the value for OA_TEST1.SCODE
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public void setScode(String scode) {
        this.scode = scode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEST1.FDATE
     *
     * @return the value of OA_TEST1.FDATE
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public Date getFdate() {
        return fdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEST1.FDATE
     *
     * @param fdate the value for OA_TEST1.FDATE
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public void setFdate(Date fdate) {
        this.fdate = fdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column OA_TEST1.FBILLID
     *
     * @return the value of OA_TEST1.FBILLID
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public String getFbillid() {
        return fbillid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column OA_TEST1.FBILLID
     *
     * @param fbillid the value for OA_TEST1.FBILLID
     *
     * @mbg.generated Wed Nov 29 21:05:22 CST 2023
     */
    public void setFbillid(String fbillid) {
        this.fbillid = fbillid;
    }
}