CREATE DATABASE IF NOT EXISTS v8sys DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci; 
CREATE DATABASE IF NOT EXISTS v8oa DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci; 
CREATE DATABASE IF NOT EXISTS v8doc DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci; 